OPENSHIFT_EXTMYSQL_DB_HOST: 127.0.0.1
OPENSHIFT_EXTMYSQL_DB_USERNAME: adminqbbDmai
#root
OPENSHIFT_EXTMYSQL_DB_PASSWORD: QPJLUqFKY4AB
OPENSHIFT_EXTMYSQL_DB_PORT: 65111
#3306
OPENSHIFT_EXTAPP_NAME: ii
OPENSHIFT_HOMEDIR:
OPENSHIFT_DATA_DIR: '/'
OPENSHIFT_BASE_URL: 'http://ii.ayfaar.org/'